/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3daaf292-3c57-45dc-b240-fd398749a9b3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Ap07D1677",
    "aws_user_pools_web_client_id": "5vil55mvacql1nqqulivsc4v33",
    "oauth": {},
    "aws_user_files_s3_bucket": "myvaccinef64cd17b5a7b40e6beb19db9206b2fc8121048-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://arqhnubiubhdzdyajwkvaealre.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-sgpglx4lnngrnaabltfyunoqum",
    "aws_content_delivery_bucket": "myvaccine-20210910221342-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://myvaccine-20210910221342-hostingbucket-prod.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
